global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "auth-service"
    static_configs:
      - targets: ["auth-service:8001"]

  - job_name: "user-service"
    static_configs:
      - targets: ["user-service:8002"]
