"""Add is_private and allowed_users

Revision ID: 9680c93d1219
Revises: 
Create Date: 2025-01-20 18:48:45.425865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9680c93d1219'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('is_private', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('portfolios', sa.Column('allowed_users', sa.JSON(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR()
            )
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('portfolios', 'allowed_users')
    op.drop_column('portfolios', 'is_private')
    # ### end Alembic commands ###
